### ISSUE TITLE
SAM parser sniffer warning

### ISSUE THREAD

**Issue by RNAer** [biocore/micronota#65]
```
/Users/zech/Dropbox/git/scikit-bio/skbio/io/registry.py:907: FormatIdentificationWarning: '_sam_sniffer' has encountered a problem.
Please send the following to our issue tracker at
https://github.com/biocore/scikit-bio/issues

Traceback (most recent call last):
  File "/Users/zech/Dropbox/git/scikit-bio/skbio/io/registry.py", line 899, in wrapped_sniffer
    return sniffer(fh)
  File "/Users/zech/Dropbox/git/micronota/micronota/parsers/sam.py", line 111, in _sam_sniffer
    assert line.startswith('@HD')
AssertionError

  FormatIdentificationWarning)
/Users/zech/Dropbox/git/scikit-bio/skbio/io/registry.py:547: FormatIdentificationWarning: <_io.BufferedReader name='/var/folders/4f/5zc7djg954dc71r037j88jwh0000gn/T/tmpqzam1xst/tmphvfj2rbr/db.diamond'> does not look like a sam file
  % (file, fmt), FormatIdentificationWarning)

```

**Comment by mortonjt** [comment]
Can you post the files in question?

**Comment by RNAer** [comment]
run "make test"
